"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/SimpleShadowSocks.py']
DATA_FILES = ['misc/ShadowSocks.png']
OPTIONS = {'argv_emulation': True, 'iconfile': 'misc/ShadowSocks.png'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
